# copyright: 2025 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_osi_saf_sea_ice
channels:
  - conda-forge
dependencies:
  # Core
  - conda-forge::python=3.10
  - conda-forge::numpy=1.26.4
  - conda-forge::jupyterlab
  - conda-forge::ipywidgets
  - conda-forge::dask
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::scipy
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::cmocean
  # External
  - conda-forge::eumdac  
  # Extension
  - conda-forge::cdsapi
  - conda-forge::copernicusmarine
  - conda-forge::lxml
  - conda-forge::cmcrameri
  - conda-forge::scikit-learn
  - conda-forge::seaborn
